Documentation for LNW usecase.
ipdk-io/networking-recipe pull request #235
Opened 2023-08-01 06:45 UTC by n-sandeep

This PR includes:
> Steps to bringup LNW.p4 with FRR
> Steps to bringup LNW.P4 with ECMP (static routes or FRR)
> Steps to bringup LNW.p4 with IPv6
> Change in p4 program compilation steps to include 'no-pedantic' option

2023-08-03 16:19 UTC, ffoulkes requested changes
The P4 files do not belong in the `docs` directory -- just .md or .rst files.

Perhaps you and I should talk to make sure we're on the same page.

2023-08-04 16:55 UTC, nupuruttarwar reviewed
Do we really need a separate readme for IPv6. Can we add a separate section in existing LNW readme wherever we assigning IP addresses?

Also, can we create a directory for p4 files
 
Still going through rest of the files, haven't finished the review fully

2023-08-04 16:55 UTC, nupuruttarwar commented on docs/features/linux_networking/es2k/readme-linux-networking-ipv6.md
> +This README describes a step-by-step procedure to run the Linux networking scenario on ES2K.
Intel IPU instead of ES2K?

2023-08-04 16:55 UTC, nupuruttarwar commented on docs/features/linux_networking/es2k/readme-linux-networking-ipv6.md
> +
remove empty line?

2023-08-04 16:55 UTC, nupuruttarwar commented on docs/features/linux_networking/es2k/readme-linux-networking-ipv6.md
> +  * Four Kernel netdevs are created by default by loading IDPF driver during ACC bring-up. You can also create more than Four netdevs. For that, we need to modify `acc_apf` parameter under `num_defau
four netdevs (lowercase f)

2023-08-04 16:55 UTC, nupuruttarwar commented on docs/features/linux_networking/es2k/readme-linux-networking-ipv6.md
> +  * In `/etc/dpcp/cfg/cp_init.cfg` file also modify default `sem_num_pages` value to the value mentioned in `/opt/p4/p4sde/share/mev_reference_p4_files/linux_networking/README_P4_CP_NWS`.
Does this really belong in notes about topology section?

2023-08-04 16:55 UTC, nupuruttarwar commented on docs/features/linux_networking/es2k/readme-linux-networking-ipv6.md
> +  * vlan1, vlan2, .... vlanN created using Linux commands and are on top of an IDPF Netdev. These VLAN ports should be equal to number of VM's that are spawned.
are created using ip link commands on top of ...

2023-08-04 16:55 UTC, nupuruttarwar commented on docs/features/linux_networking/es2k/readme-linux-networking-ipv6.md
> +  * vlan1, vlan2, .... vlanN created using Linux commands and are on top of an IDPF Netdev. These VLAN ports should be equal to number of VM's that are spawned.
These VLAN port are mapped 1:1 to VMs?

2023-08-04 16:55 UTC, nupuruttarwar commented on docs/features/linux_networking/es2k/readme-linux-networking-ipv6.md
> +  * br-int, VxLAN ports are created using ovs-vsctl command provided by the networking recipe and all the vlan ports are attached to br-int using ovs-vsctl command.
Can we separate 2nd part of this sentence?

All VLAN port representors and VxLAN ports are part of same broadcast domain (br-int)?

2023-08-04 17:03 UTC, nupuruttarwar commented on docs/features/linux_networking/es2k/readme-linux-networking-with-frr.md
> +These VSI values can be checked with `/usr/bin/cli_client -q -c` command on IMC. This command provides VSI ID, Vport ID, and corresponding MAC addresses for all
for the following:

2023-08-04 17:03 UTC, nupuruttarwar commented on docs/features/linux_networking/es2k/readme-linux-networking-with-frr.md
> +- VLAN Tagged packets are not supported.
Can we instead say something like current P4 doesn't cover Vlan tagged packets?

not supported gives the impression that IPU may not be capable of it?

2023-08-04 22:34 UTC, ffoulkes commented
> Also, can we create a directory for p4 files

Documentation only under the **docs** directory. The P4 files remain part of the **p4src** directory.

2023-09-08 14:43 UTC, closed without merging