Update build instructions for stratum-deps
ipdk-io/networking-recipe pull request #334
Opened 2023-11-09 21:06 UTC by ffoulkes

- Update stratum dependencies build guides to reference the `stratum-deps` repository.

2023-11-09 21:15 UTC, 5abeel requested changes

2023-11-09 21:15 UTC, 5abeel commented on docs/guides/deps/building-stratum-deps.md
> +There a couple of things to do before you build the dependencies.
```suggestion
There are a couple of things to do before you build the dependencies.
```

2023-11-09 21:15 UTC, 5abeel commented on docs/guides/deps/building-acc-stratum-deps.md
> +There a couple of things to do before you build the dependencies.
```suggestion
There are a couple of things to do before you build the dependencies.
```

2023-11-09 21:15 UTC, 5abeel commented on docs/guides/deps/building-acc-stratum-deps.md
> +Source the file that the defines the
```suggestion
Source the file that defines the
```

2023-11-09 21:15 UTC, 5abeel commented on docs/guides/deps/building-stratum-deps.md
> +### Github repository
`GitHub` with uppercase `H`?

2023-11-09 21:29 UTC, ffoulkes commented
Correct on all count. Thanks.

2023-11-09 21:31 UTC, 5abeel approved these changes
LGTM

2023-11-10 17:31 UTC, bharticemk approved these changes
LGTM

2023-11-10 17:31 UTC, nupuruttarwar approved these changes
LGTM

2023-11-10 17:33 UTC, n-sandeep approved these changes
LGTM

2023-11-10 17:58 UTC, merged